# Generated by Django 3.2.16 on 2023-09-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20230928_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state_province_region',
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('...', 'Cero'), (' Arica y Parinacota', 'Uno'), (' Tarapaca', 'Dos'), (' Antofagasta', 'Tres'), ('Atacama', 'Cuatro'), ('Coquimbo', 'Cinco'), ('Valparaiso', 'Seis'), ('Metropolitana', 'Siete'), ('O`higgins', 'Ocho'), ('Maule', 'Nueve'), ('Ñuble', 'Diez'), ('Biobío', 'Once'), ('La Araucania', 'Doce'), ('Los Rios', 'Trece'), ('Los Lagos', 'Catorce'), ('Aysén', 'Quince'), ('Magallanes', 'Dieciseis')], default='...', max_length=255),
        ),
    ]
