# Generated by Django 3.2.16 on 2023-10-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20231023_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
    ]
