# Generated by Django 3.2.16 on 2023-08-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metaproduct', '0001_initial'),
        ('product', '0003_galleryproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationpiedrajoya',
            options={'verbose_name': 'Piedrasin', 'verbose_name_plural': 'Piedrasin'},
        ),
        migrations.CreateModel(
            name='JoyaMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.joyas')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metaproduct.material')),
            ],
        ),
    ]
