# Generated by Django 3.2.16 on 2023-11-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20230820_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='piedras',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
