# Generated by Django 3.2.16 on 2023-10-23 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0010_auto_20231023_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.IntegerField(unique=True)),
                ('payment_id', models.IntegerField(unique=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order')),
            ],
        ),
    ]
