# Generated by Django 3.2.16 on 2023-10-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20230930_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country_region',
            field=models.CharField(choices=[('...', 'Cero'), ('Arica y Parinacota', 'Uno'), ('Tarapaca', 'Dos'), ('Antofagasta', 'Tres'), ('Atacama', 'Cuatro'), ('Coquimbo', 'Cinco'), ('Valparaiso', 'Seis'), ('Metropolitana', 'Siete'), ('O`higgins', 'Ocho'), ('Maule', 'Nueve'), ('Ñuble', 'Diez'), ('Biobío', 'Once'), ('La Araucania', 'Doce'), ('Los Rios', 'Trece'), ('Los Lagos', 'Catorce'), ('Aysén', 'Quince'), ('Magallanes', 'Dieciseis')], default='...', max_length=255),
        ),
    ]
