# Generated by Django 3.2.16 on 2023-08-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='NombrePiedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mohs', models.DecimalField(decimal_places=3, max_digits=7)),
                ('origen', models.CharField(choices=[('Volcanico', 'VOLCANICO'), ('Sedimentario', 'SEDIMENTARIO'), ('Metamorfico', 'METAMORFICO')], max_length=55)),
            ],
            options={
                'verbose_name': 'PiedraTipo',
                'verbose_name_plural': 'Tipos de piedra',
            },
        ),
    ]
