# Generated by Django 3.2.16 on 2023-09-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='direction',
        ),
    ]
