# Generated by Django 3.2.16 on 2023-09-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_delete_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='price',
        ),
        migrations.AddField(
            model_name='shipping',
            name='description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
