# Generated by Django 3.2.16 on 2023-11-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
