# Generated by Django 3.2.16 on 2023-11-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_auto_20230928_0047'),
        ('orders', '0015_order_deliverynumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_name',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shipping.shipping'),
            preserve_default=False,
        ),
    ]
