# Generated by Django 3.2.16 on 2023-11-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_auto_20230928_0047'),
        ('orders', '0016_auto_20231115_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shipping.shipping'),
        ),
    ]
